on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Build
        run: hugo --minify
        env:
          HUGO_PARAMS_PAGE_MAPBOX_ACCESSTOKEN: ${{ secrets.MAPBOX_ACCESSTOKEN }}
          HUGO_PARAMS_PAGE_COMMENT_VALINE_APPID: ${{ secrets.LEANCLOUD_APPID }}
          HUGO_PARAMS_PAGE_COMMENT_VALINE_APPKEY: ${{ secrets.LEANCLOUD_APPKEY }}
          HUGO_PARAMS_ANALYTICS_GOOGLE_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
          HUGO_PARAMS_ANALYTICS_UMAMI_DATA_WEBSITE_ID: ${{ secrets.ANALYTICS_UMAMI_DATA_WEBSITE_ID }}
          HUGO_PARAMS_ANALYTICS_UMAMI_SRC: ${{ secrets.ANALYTICS_UMAMI_SRC }}
          HUGO_PARAMS_ANALYTICS_UMAMI_DATA_HOST_URL: ${{ secrets.ANALYTICS_UMAMI_DATA_HOST_URL }}
          HUGO_PARAMS_ANALYTICS_UMAMI_DATA_DOMAINS: ${{ secrets.ANALYTICS_UMAMI_DATA_DOMAINS }}
          HUGO_PARAMS_VERIFICATION_GOOGLE: ${{ secrets.VERIFICATION_GOOGLE }}
          HUGO_PARAMS_VERIFICATION_YANDEX: ${{ secrets.VERIFICATION_YANDEX }}

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -azr -vv --checksum --delete
          path: public/
          remote_path: ${{ secrets.REMOTE_TARGET }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: ${{ secrets.REMOTE_PORT }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
