on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Build
        run: hugo --minify
        env:
          HUGOxPARAMSxPAGExMAPBOXxACCESSTOKEN: ${{ secrets.MAPBOX_ACCESSTOKEN }}
          HUGOxPARAMSxPAGExCOMMENTxVALINExAPPID: ${{ secrets.LEANCLOUD_APPID }}
          HUGOxPARAMSxPAGExCOMMENTxVALINExAPPKEY: ${{ secrets.LEANCLOUD_APPKEY }}
          HUGOxPARAMSxANALYTICSxGOOGLExID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
          HUGOxPARAMSxANALYTICSxUMAMIxDATA_WEBSITE_ID: ${{ secrets.ANALYTICS_UMAMI_DATA_WEBSITE_ID }}
          HUGOxPARAMSxANALYTICSxUMAMIxSRC: ${{ secrets.ANALYTICS_UMAMI_SRC }}
          HUGOxPARAMSxANALYTICSxUMAMIxDATA_DOMAINS: ${{ secrets.ANALYTICS_UMAMI_DATA_DOMAINS }}
          HUGOxPARAMSxVERIFICATIONxGOOGLE: ${{ secrets.VERIFICATION_GOOGLE }}
          HUGOxPARAMSxVERIFICATIONxYANDEX: ${{ secrets.VERIFICATION_YANDEX }}

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -azr -vv --checksum --delete
          path: public/
          remote_path: ${{ secrets.REMOTE_TARGET }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: ${{ secrets.REMOTE_PORT }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
