on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
          submodules: 'recursive'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: Build
        run: hugo --minify
        env:
          HUGO_PARAMS_PAGE_MAPBOX_ACCESSTOKEN: ${{ secrets.MAPBOX_ACCESSTOKEN }}
          HUGO_PARAMS_PAGE_COMMENT_VALINE_APPID: ${{ secrets.LEANCLOUD_APPID }}
          HUGO_PARAMS_PAGE_COMMENT_VALINE_APPKEY: ${{ secrets.LEANCLOUD_APPKEY }}
          HUGO_PARAMS_ANALYTICS_GOOGLE_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avcz --delete --append-verify
          path: public/
          remote_path: ${{ secrets.REMOTE_TARGET }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: ${{ secrets.REMOTE_PORT }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
